version: '3'
services:
  backend:
    restart: always
    image: school-listing/backend
    links:
      - mongo
    ports:
      - "3000:3000"
  web:
    restart: always
    image: school-listing/frontend
    ports:
      - "8100:80"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"